stages:
  format_datasets:
    desc: Format datasets with the specified prompt templates
    cmd: python -m src.stages.format_datasets --config=params.yaml
    deps:
      - ${base.datasets_dir}/${format_datasets.raw_dir_path}/
      - src/stages/format_datasets.py
    outs:
      - ${base.datasets_dir}/${format_datasets.formatted_dir_path}/
    params:
      - base
      - datasets
      - format_datasets
  generate_answers:
    desc: Generate answers for the formatted datasets with the specified model
    cmd: python -m src.stages.generate_answers --config=params.yaml --model=${generate_answers.model}
    deps:
      - ${base.datasets_dir}/${format_datasets.formatted_dir_path}/
      - src/stages/generate_answers.py
    outs:
      - ${base.generations_dir}/
    params:
      - base
      - datasets
      - format_datasets
      - generate_answers
  evaluate_answers:
    desc: Evaluate generations against the ground truth
    cmd: python -m src.stages.evaluate_answers --config=params.yaml --model=${generate_answers.model}
    deps:
      - ${base.datasets_dir}/${format_datasets.formatted_dir_path}/
      - ${base.generations_dir}/
      - src/stages/evaluate_answers.py
    outs:
      - ${base.evaluations_dir}/
    params:
      - base
      - datasets
      - generate_answers
      - format_datasets
  capture_activations:
    desc: Capture activations at the specified layers for all generated answers
    cmd: python -m src.stages.capture_activations --config=params.yaml --model=${generate_answers.model}
    deps:
      - ${base.generations_dir}/
      - src/stages/capture_activations.py
    outs:
      - ${base.activations_dir}/
    params:
      - base
      - models
      - datasets
      - generate_answers
      - capture_activations
metrics:
  - ${base.evaluations_dir}/${generate_answers.model}/metrics.json