base:
  project_name: correctness-model-internals
  log_level: DEBUG
  models_dir: "../models"
  datasets_dir: "../datasets"

datasets:
  mmlu:
    answer_map: ["A", "B", "C", "D"]
    subsets:
      - "high_school_mathematics"
      - "college_mathematics"
      - "abstract_algebra"

models:
  llama3_8b_chat:
    dir_path: "llama3_8b_chat_hf"
    family: "Llama3"
    size: "8B"
    type: "chat"

format_dataset:
  dir_path: "formatted"
  prompts:
    base: "The following is a multiple choice question (with answers) about {topic}."
    # cot: |-
    #   The following is a multiple choice question (with answers) about {topic}.
    #   Think step by step about the problem. Display your choice at the end.
