base:
  project_name: correctness-model-internals
  log_level: DEBUG
  models_dir: ../models
  datasets_dir: ./datasets
  generations_dir: ./generations
  evaluations_dir: ./evaluations
  activations_dir: ./activations
  classification_stats_dir: ./classification_stats

datasets:
  mmlu:
    answer_type: multiple_choice
    answer_map: [A, B, C, D]
    eval_type: constrained_tokens
    subsets:
      - high_school_mathematics
      - college_mathematics
      - abstract_algebra
    prompts:
      base: The following is a multiple choice question (with answers). Give your answer with a single letter corresponding to the correct answer.
  cities_10k:
    answer_type: open_ended
    subsets:
      - main
    format: csv
    eval_type: answers_map
    answers_map_path: eval_map.json
    col_map:
      prompt: question
      answer: correct_answer
    prompts:
      base: |-
        I am going to ask you a question about cities. End your sentence with <|eot_id|>.
        Here are some examples of questions that might help you:
        ---
        Question: In which country is the city of Barcelona located?
        Answer: Spain<|eot_id|>
        ---
        Question: In which country is the city of Berlin located?
        Answer: Germany<|eot_id|>
        ---
        Question: In which country is the city of Beijing located?
        Answer: China<|eot_id|>
        ---
        Question:
  birth_years_4k:
    answer_type: open_ended
    subsets:
      - main
    format: csv
    eval_type: exact_match
    col_map:
      prompt: question
      answer: correct_answer
    prompts:
      base: |-
        I am going to ask you what year a person was born. End your sentence with <|eot_id|>.
        Here are some examples of questions that might help you:
        ---
        Question: What year was Barack Obama born? 
        Answer: 1961<|eot_id|>
        ---
        Question: What year was Vladimir Putin born? 
        Answer: 1952<|eot_id|>
        ---
        Question: What year was Xi Jinping born? 
        Answer: 1953<|eot_id|>
        ---
        Question:
  medals_9k:
    answer_type: open_ended
    subsets:
      - main
    format: csv
    eval_type: answers_map
    answers_map_path: eval_map.json
    col_map:
      prompt: question
      answer: correct_answer
    prompts:
      base: |-
        I am going to ask you a question about the olympics. End your sentence with <|eot_id|>.
        Here are some examples of questions that might help you:
        ---
        Question: Which country won gold in Gymnastics Women's Team All-Around in the 1928 Summer Olympics?
        Answer: Netherlands<|eot_id|> 
        ---
        Question: Which country won gold in Hockey Women's Hockey in the 2004 Summer Olympics? Answer: Germany<|eot_id|> 
        ---
        Question: Which country won gold in Fencing Men's Sabre, Individual in the 1964 Summer Olympics?
        Answer: Hungary<|eot_id|>
        ---
        Question:
  football_leagues_1k:
    answer_type: open_ended
    subsets:
      - main
    format: csv
    eval_type: answers_map
    answers_map_path: eval_map.json
    col_map:
      prompt: question
      answer: correct_answer
    prompts:
      base: |-
        I am going to ask you a question about football. End your sentence with <|eot_id|>.
        Here are some examples of questions that might help you:
        ---
        Question: Which team finished in position 10 in the 2010-2011 Premier League?
        Answer: Sunderland<|eot_id|> 
        ---
        Question: Which team finished in position 19 in the 2020-2021 La Liga?
        Answer: Valladolid<|eot_id|> 
        ---
        Question: Which team finished in position 13 in the 2019-2020 Serie A?
        Answer: Udinese<|eot_id|>
        ---
        Question:
  gsm8k:
    answer_type: open_ended
    answer_delim: "####"
    answer_regex: (?<=\$\\boxed\{)\d+(?=\}\$)
    eval_type: regex_match
    subsets:
      - main
    prompts:
      # TODO: replace with other n-shot examples
      base_3_shot: |-
        Give your answer in this format: $\boxed{answer}$
        Here are some examples to help you understand the format:
        ---
        Question: Weng earns $12 an hour for babysitting. Yesterday, she just did 50 minutes of babysitting. How much did she earn?
        Answer: $\boxed{10}$
        ---
        Question: Julie is reading a 120-page book. Yesterday, she was able to read 12 pages and today, she read twice as many pages as yesterday. If she wants to read half of the remaining pages tomorrow, how many pages should she read?
        Answer: $\boxed{42}$
        ---
        Question: Mark has a garden with flowers. He planted plants of three different colors in it. Ten of them are yellow, and there are 80% more of those in purple. There are only 25% as many green flowers as there are yellow and purple flowers. How many flowers does Mark have in his garden?
        Answer: $\boxed{35}$
        ---
        Question:
      cot_3_shot: |-
        Think step by step about the following problem.
        Give your answer in this format: $\boxed{answer}$
        Here are some examples to help you understand the format:
        ---
        Question: Weng earns $12 an hour for babysitting. Yesterday, she just did 50 minutes of babysitting. How much did she earn?
        Reasoning: Weng earns 12/60 = $12/60=0.20.2 per minute. Working 50 minutes, she earned 0.2 x 50 = $0.2*50=1010.
        Final answer: $\boxed{10}$
        ---
        Question: Julie is reading a 120-page book. Yesterday, she was able to read 12 pages and today, she read twice as many pages as yesterday. If she wants to read half of the remaining pages tomorrow, how many pages should she read?
        Reasoning: Julie read 12 x 2 = 12*2=2424 pages today. So she was able to read a total of 12 + 24 = 12+24=3636 pages since yesterday. There are 120 - 36 = 120-36=8484 pages left to be read. Since she wants to read half of the remaining pages tomorrow, then she should read 84/2 = 84/2=4242 pages.
        Final answer: $\boxed{42}$
        ---
        Question: Mark has a garden with flowers. He planted plants of three different colors in it. Ten of them are yellow, and there are 80% more of those in purple. There are only 25% as many green flowers as there are yellow and purple flowers. How many flowers does Mark have in his garden?
        Reasoning: There are 80/100 * 10 = 80/100*10=88 more purple flowers than yellow flowers. So in Mark's garden, there are 10 + 8 = 10+8=1818 purple flowers. Purple and yellow flowers sum up to 10 + 18 = 10+18=2828 flowers. That means in Mark's garden there are 25/100 * 28 = 25/100*28=77 green flowers. So in total Mark has 28 + 7 = 28+7=3535 plants in his garden.
        Final answer: $\boxed{35}$
        ---
        Question:

models:
  llama3_8b_chat:
    dir_path: llama3_8b_chat_hf
    eos_token: <\|eot_id\|>
  llama3_8b_cot:
    dir_path: llama3_8b_cot_numina_hf
    eos_token: <\|eot_id\|>
  llama3_3b_chat:
    dir_path: llama3_3b_chat_hf

format_datasets:
  raw_dir_path: raw
  formatted_dir_path: formatted
  generation_delimiter: "Answer:" # {str (e.g., "Answer:"), false}

generate_answers:
  model: llama3_3b_chat
  max_dataset_size: 10 # false or integer
  sample_strategy: first_n # {first_n, random}
  max_new_tokens: 1024
  stop_word: "}$"
  batch_size: 25

capture_activations:
  input_type: [prompt_only, prompt_answer] # {prompt_only, prompt_answer}
