version: '3'

vars:
  PYTHON: '{{.ROOT_DIR}}/venv/bin/python'
  CONFIG: '{{.ROOT_DIR}}/params.yml'

tasks:
  format-datasets:
    desc: Prepare benchmark datasets for question-answering
    cmds:
      - '{{.PYTHON}} -m src.stages.format_datasets --config={{.CONFIG}}'
  generate-answers:
    desc: Generate answers for the benchmark datasets
    cmds:
      - '{{.PYTHON}} -m src.stages.generate_answers --config={{.CONFIG}} --model={{.CLI_ARGS}}'
  eval-answers:
    desc: Evaluate answers for the benchmark datasets
    cmds:
      - '{{.PYTHON}} -m src.stages.evaluate_answers --config={{.CONFIG}} --model={{.CLI_ARGS}}'
  dep-lock:
    desc: Update the project's lockfiles from the requirements-<env>.in files
    cmds:
      - 'pip-compile'
      - 'pip-compile requirements-dev.in'
      - 'pip-compile requirements-pred.in'
  format:
    desc: Format the code using black and isort
    cmds:
      - '{{.PYTHON}} -m black src'
      - '{{.PYTHON}} -m isort src'