base:
  project_name: correctness-model-internals
  log_level: DEBUG
  models_dir: ../models
  datasets_dir: ./datasets
  generations_dir: ./generations
  evaluations_dir: ./evaluations
  activations_dir: ./activations
  classification_stats_dir: ./classification_stats

datasets:
  # trivia_qa:
  #   hf_repo_id: mandarjoshi/trivia_qa
  #   answer_type: open_ended
  #   subsets:{eos_token}
  #     - rc
  #   prompts:
  #     base: |-
  #       I am going to ask you a question. End your sentence with {eos_token}.
  #       Here are some examples of questions that might help you:
  #       ---
  #       Which American-born Sinclair won the Nobel Prize for Literature in 1930?
  #       Answer: Upton Sinclair{eos_token}
  #       ---
  #       Question:
  # mmlu:
  #   hf_repo_id: cais/mmlu
  #   answer_type: multiple_choice
  #   answer_map: [A, B, C, D]
  #   eval_type: constrained_tokens
  #   subsets:
  #     - high_school_mathematics
  #     - college_mathematics
  #     - abstract_algebra
  #   prompts:
  #     base: The following is a multiple choice question (with answers). Give your answer with a single letter corresponding to the correct answer.
  cities_10k:
    answer_type: open_ended
    subsets:
      - main
    format: csv
    eval_type: answers_map
    max_new_tokens: 128
    stop_words: ["{eos_token}", "\n"]
    answers_map_path: eval_map.json
    col_map:
      prompt: question
      answer: correct_answer
    prompts:
        verbalized_confidence_raw:
          text: |-
            I am going to ask you about your confidence to answer a question.
            The confidence indicates how likely you think your answer will be true.
            Please respond with only a percentage and end with {eos_token}, so your answer should be following the format 'Answer: (percentage)%{eos_token}'.
            How confident are you that you can answer correctly '
          generation_delimiter: "'?\nAnswer:"
        verbalized_confidence_3_shot:
          text: |-
            I am going to ask you about your confidence to answer a question. 
            Please respond with only a percentage and end with {eos_token}. The confidence indicates how likely you think your answer will be true. 
            ---
            How confident are you that you can answer correctly 'What is the last digit of pi'?
            Answer: 10%{eos_token}.
            ---
            How confident are you that you can answer correctly 'Will a fair coin land on heads or tails'?
            Answer: 50%{eos_token}.
            ---
            How confident are you that you can answer correctly 'What is 1+1?'? 
            Answer: 90%{eos_token}. 
            ---
            How confident are you that you can answer correctly '
          generation_delimiter: "'?\nAnswer:"
  birth_years_4k:
    answer_type: open_ended
    subsets:
      - main
    format: csv
    eval_type: exact_match
    max_new_tokens: 128
    stop_words: ["{eos_token}", "\n"]
    col_map:
      prompt: question
      answer: correct_answer
    prompts:
        verbalized_confidence_raw:
          text: |-
            I am going to ask you about your confidence to answer a question.
            The confidence indicates how likely you think your answer will be true.
            Please respond with only a percentage and end with {eos_token}, so your answer should be following the format 'Answer: (percentage)%{eos_token}'.
            How confident are you that you can answer correctly '
          generation_delimiter: "'?\nAnswer:"
        verbalized_confidence_3_shot:
          text: |-
            I am going to ask you about your confidence to answer a question. 
            Please respond with only a percentage and end with {eos_token}. The confidence indicates how likely you think your answer will be true. 
            ---
            How confident are you that you can answer correctly 'What is the last digit of pi'?
            Answer: 10%{eos_token}.
            ---
            How confident are you that you can answer correctly 'Will a fair coin land on heads or tails'?
            Answer: 50%{eos_token}.
            ---
            How confident are you that you can answer correctly 'What is 1+1?'? 
            Answer: 90%{eos_token}. 
            ---
            How confident are you that you can answer correctly '
          generation_delimiter: "'?\nAnswer:"
  medals_9k:
    answer_type: open_ended
    subsets:
      - main
    format: csv
    eval_type: answers_map
    max_new_tokens: 128
    stop_words: ["{eos_token}", "\n"]
    answers_map_path: eval_map.json
    col_map:
      prompt: question
      answer: correct_answer
    prompts:
        verbalized_confidence_raw:
          text: |-
            I am going to ask you about your confidence to answer a question.
            The confidence indicates how likely you think your answer will be true.
            Please respond with only a percentage and end with {eos_token}, so your answer should be following the format 'Answer: (percentage)%{eos_token}'.
            How confident are you that you can answer correctly '
          generation_delimiter: "'?\nAnswer:"
        verbalized_confidence_3_shot:
          text: |-
            I am going to ask you about your confidence to answer a question. 
            Please respond with only a percentage and end with {eos_token}. The confidence indicates how likely you think your answer will be true. 
            ---
            How confident are you that you can answer correctly 'What is the last digit of pi'?
            Answer: 10%{eos_token}.
            ---
            How confident are you that you can answer correctly 'Will a fair coin land on heads or tails'?
            Answer: 50%{eos_token}.
            ---
            How confident are you that you can answer correctly 'What is 1+1?'? 
            Answer: 90%{eos_token}. 
            ---
            How confident are you that you can answer correctly '
          generation_delimiter: "'?\nAnswer:"
  trivia_qa_2_60k:
    answer_type: open_ended
    subsets:
      - main
    format: csv
    eval_type: list_of_answers
    max_new_tokens: 128
    stop_words: ["{eos_token}", "\n"]
    col_map:
      prompt: question
      answer: correct_answer
    prompts:
        verbalized_confidence_raw:
          text: |-
            I am going to ask you about your confidence to answer a question.
            The confidence indicates how likely you think your answer will be true.
            Please respond with only a percentage and end with {eos_token}, so your answer should be following the format 'Answer: (percentage)%{eos_token}'.
            How confident are you that you can answer correctly '
          generation_delimiter: "'?\nAnswer:"
        verbalized_confidence_3_shot:
          text: |-
            I am going to ask you about your confidence to answer a question. 
            Please respond with only a percentage and end with {eos_token}. The confidence indicates how likely you think your answer will be true. 
            ---
            How confident are you that you can answer correctly 'What is the last digit of pi'?
            Answer: 10%{eos_token}.
            ---
            How confident are you that you can answer correctly 'Will a fair coin land on heads or tails'?
            Answer: 50%{eos_token}.
            ---
            How confident are you that you can answer correctly 'What is 1+1?'? 
            Answer: 90%{eos_token}. 
            ---
            How confident are you that you can answer correctly '
          generation_delimiter: "'?\nAnswer:"
  math_operations_6k:
    answer_type: open_ended
    subsets:
      - main
    format: csv
    eval_type: exact_match
    max_new_tokens: 128
    stop_words: ["{eos_token}", "\n"]
    col_map:
      prompt: question
      answer: correct_answer
    prompts:
        verbalized_confidence_raw:
          text: |-
            I am going to ask you about your confidence to answer a question.
            The confidence indicates how likely you think your answer will be true.
            Please respond with only a percentage and end with {eos_token}, so your answer should be following the format 'Answer: (percentage)%{eos_token}'.
            How confident are you that you can answer correctly '
          generation_delimiter: "'?\nAnswer:"
        verbalized_confidence_3_shot:
          text: |-
            I am going to ask you about your confidence to answer a question. 
            Please respond with only a percentage and end with {eos_token}. The confidence indicates how likely you think your answer will be true. 
            ---
            How confident are you that you can answer correctly 'What is the last digit of pi'?
            Answer: 10%{eos_token}.
            ---
            How confident are you that you can answer correctly 'Will a fair coin land on heads or tails'?
            Answer: 50%{eos_token}.
            ---
            How confident are you that you can answer correctly 'What is 1+1?'? 
            Answer: 90%{eos_token}. 
            ---
            How confident are you that you can answer correctly '
          generation_delimiter: "'?\nAnswer:"
  gsm8k:
    hf_repo_id: openai/gsm8k
    answer_type: open_ended
    answer_delim: "####"
    answer_regex: (?<=\$\\boxed\{)\d+(?=\}\$)
    eval_type: regex_match
    max_new_tokens: 1024
    stop_words: ["}$"]
    subsets:
      - main
    prompts:
        verbalized_confidence_raw:
          text: |-
            I am going to ask you about your confidence to answer a question.
            The confidence indicates how likely you think your answer will be true.
            Please respond with only a percentage and end with {eos_token}, so your answer should be following the format 'Answer: (percentage)%{eos_token}'.
            How confident are you that you can answer correctly '
          generation_delimiter: "'?\nAnswer:"
        verbalized_confidence_3_shot:
          text: |-
            I am going to ask you about your confidence to answer a question. 
            Please respond with only a percentage and end with {eos_token}. The confidence indicates how likely you think your answer will be true. 
            ---
            How confident are you that you can answer correctly 'What is the last digit of pi'?
            Answer: 10%{eos_token}.
            ---
            How confident are you that you can answer correctly 'Will a fair coin land on heads or tails'?
            Answer: 50%{eos_token}.
            ---
            How confident are you that you can answer correctly 'What is 1+1?'? 
            Answer: 90%{eos_token}. 
            ---
            How confident are you that you can answer correctly '
          generation_delimiter: "'?\nAnswer:"


models:
  llama3.1_8b_chat:
    hf_repo_id: meta-llama/Llama-3.1-8B 
    dir_path: llama3.1_8b_chat
    eos_token: <|end_of_text|>
    max_length: 1024
    num_layers: 32
  llama3_3b_chat:
    hf_repo_id: meta-llama/Llama-3.2-3B 
    dir_path: llama3_3b_chat_hf
    eos_token: <|end_of_text|>
    max_length: 1024
    num_layers: 28
  mistral_7b_instruct:
    hf_repo_id: mistralai/Mistral-7B-Instruct-v0.3
    dir_path: mistral_7b_instruct
    eos_token: </s>
    max_length: 1024
    num_layers: 32
  gemma_2_9b_it:
    hf_repo_id: google/gemma-2-9b-it
    dir_path: gemma_2_9b_it
    eos_token: <|eot_id|> # TODO: placeholder
    max_length: 1024
    num_layers: 42 
  deepseek_qwen_32b:
    hf_repo_id: deepseek-ai/DeepSeek-R1-Distill-Qwen-32B
    dir_path: deepseek_qwen_32b
    eos_token: <|eot_id|> # TODO: placeholder
    max_length: 1024 
    num_layers: 64 
  llama3.3_70b:
    hf_repo_id: meta-llama/Llama-3.3-70B-Instruct
    dir_path: llama3.3_70b
    eos_token: <|end_of_text|>
    max_length: 1024
    num_layers: 80
  qwen_2.5_7b_instruct:
    hf_repo_id: Qwen/Qwen2.5-7B-Instruct
    dir_path: qwen_2.5_7b_instruct
    eos_token: <|im_end|>
    max_length: 1024
    num_layers: 28
  ministral_8b_instruct:
    hf_repo_id: mistralai/Ministral-8B-Instruct-2410
    dir_path: ministral_8b_instruct
    eos_token: </s> # TODO: placeholder
    max_length: 1024
    num_layers: 36





format_datasets:
  raw_dir_path: raw
  formatted_dir_path: formatted
  generation_delimiter: "Answer:" # {str (e.g., "Answer:"), false}

generate_answers:
  models:
    - ministral_8b_instruct
    # - qwen_2.5_7b_instruct
    - llama3.1_8b_chat
    - mistral_7b_instruct 
  max_dataset_size: false
  sample_strategy: first_n
  batch_size: 100
  inference_engine: vllm

inference_engines:
  litellm:
    qps_limit: 50 # API rate limit: queries per second

evaluate_answers:
  idk_match: [i don't, i do not, can you, more information, i need, unsure, not sure, uncertain, not certain, not understand, don't understand, i can't, i can not, i'm not, i am not]
  idk_class_value: N/A
  llm_judge:
    datasets: [trivia_qa_2_60k]
    inference_engine: litellm
    model: together_ai/Qwen/Qwen2.5-72B-Instruct-Turbo
    prompt:
      system: |-
        You are an expert evaluator determining if an answer is semantically correct. Focus on meaning rather than exact wording. An answer can be correct even if it differs from the ground truth in phrasing.

        Respond with 1 if the answer is correct, 0 if it is incorrect, and N/A if the answer is "I don't know" or similar.

        Examples:
          
        Question: What is 10 plus 5?
        Answer given: Fifteen
        Expected ground truth: 15
        Judgement: 1

        Question: In which country is the city of Kostomloty Pierwsze located?
        Answer given: I'm sorry, but I don't have that information.
        Expected ground truth: Poland
        Judgement: N/A
      user: |-
        Question: {question}
        Answer given: {answer}
        Expected ground truth: {ground_truth}
        Judgement:

capture_activations:
  raw_dir_path: raw
  batch_size: 20
  input_type: [prompt_only, prompt_answer] # {prompt_only, prompt_answer}
  layers: -1 # must be a string due to dvc limitations. Either `-1` for all layers, or `"[0, 1, ...]"` for specific layers
  step_size: 2 # capture every nth layer, default is 1


postprocess_activations:
  postprocessed_dir_path: postprocessed
  methods: [pca] # {pca, tsne}
  tsne:
    n_components: 2
    perplexity: 30
    n_iter: 1000
    random_state: 42
  pca:
    n_components: 2
    random_state: 42
